### PR TITLE
Changes to parse Models added via nwidart/laravel-modules

### PR DESCRIPTION
**Pull request by dedanirungu**
The changes to allow the package to parse models adding in modules used via nwidart/laravel-modules.

### CODE REVIEW

**Comment by legodion** [comment]
What if I just added a config file that lets you specify the path to your models instead?

Would that work for your package?

**Comment by dedanirungu** [comment]
> What if I just added a config file that lets you specify the path to your models instead?
> 
> Would that work for your package?

It might not work because the structure of files is as follows;
[project_path]/Modules/[Module Name]/Entities/[Model Name].php

Unless the config takes wildcard eg
[project_path]/Modules/*/Entities/*.php


for example my system has following structure.

Blogs
/var/www/html/laravel/Modules/Blog/Entities/Post.php
/var/www/html/laravel/Modules/Blog/Entities/Category.php

Media
/var/www/html/laravel/Modules/Media/Entities/File.php

School
/var/www/html/laravel/Modules/School/Entities/Student.php

**Comment by dedanirungu** [comment]
What is your decision on this pull request?

**Comment by legodion** [comment]
See comment in issues.

**Comment by legodion** [comment]
closing this as you've mentioned you're using a fork instead

**Pull request closed without merging**
